### ISSUE TITLE
Names of features in tree_stem?

### ISSUE THREAD

**Issue by wincentbalin** [amakukha/stemmers_ukrainian#1]
Dear @amakukha , would you like to name the features `f1` to `f10` used in https://github.com/amakukha/stemmers_ukrainian/blob/master/src/tree_stem.py ?

**Comment by amakukha** [comment]
Hello, @wincentbalin ,
As is clear from `word_to_vec` method, the features are last 10 letters of a word. f1 = last letter, f2 = penultimate letter, etc. By convention, if a word is shorter than 10 letters, then remaining features are zero (which is value of space).

Since most of this code is computer-generated, I didn't care to name the variables.

**Comment by wincentbalin** [comment]
Thank you very much! As this is clear now, I am going to close this issue.
